import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { chmod, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import test from "node:test";

const execFileAsync = promisify(execFile);

async function writeRetryAccountingStub(stubPath) {
  await writeFile(stubPath, `#!/usr/bin/env bash
set -euo pipefail

agent=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --agent)
      agent="$2"
      shift 2
      ;;
    --cwd)
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

prompt="$(cat)"
output_file="$(
  printf '%s\\n' "$prompt" |
    sed -n -E 's/^([0-9]+\\. )?Write the (plan|deliverable|verdict) to: (.*)$/\\3/p' |
    tail -1
)"

if [ -z "$output_file" ]; then
  echo "stub could not find output path in prompt" >&2
  exit 1
fi

mkdir -p "$(dirname "$output_file")"

case "$agent" in
  codex)
    if printf '%s\\n' "$prompt" | grep -q "Give a verdict"; then
      count_file="$CPB_TEST_STATE/verify-count"
      count="$(cat "$count_file" 2>/dev/null || echo 0)"
      count="$((count + 1))"
      printf '%s\\n' "$count" > "$count_file"
      case "$count" in
        1)
          printf 'VERDICT: FAIL\\nReason: artifact_stale, regenerate the verification bundle.\\n' > "$output_file"
          ;;
        2|3)
          printf 'VERDICT: FAIL\\nThe implementation still misses acceptance criteria.\\n' > "$output_file"
          ;;
        *)
          printf 'VERDICT: PASS\\nAll acceptance criteria are now satisfied.\\n' > "$output_file"
          ;;
      esac
    else
      printf '# Plan: retry accounting regression\\n\\nAcceptance-Criteria:\\n- pipeline keeps fix attempts separate from verifier retries\\n' > "$output_file"
    fi
    ;;
  claude)
    count_file="$CPB_TEST_STATE/execute-count"
    count="$(cat "$count_file" 2>/dev/null || echo 0)"
    count="$((count + 1))"
    printf '%s\\n' "$count" > "$count_file"
    printf '# Deliverable %s\\n\\nplan-ref: 001\\n\\nGenerated by retry accounting stub.\\n' "$count" > "$output_file"
    ;;
  *)
    echo "unexpected agent: $agent" >&2
    exit 1
    ;;
esac
`, "utf8");
  await chmod(stubPath, 0o755);
}

test("run-pipeline keeps verifier evidence retries from consuming executor fix attempts", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "cpb-retry-accounting-"));
  const cpbRoot = path.join(root, "cpb");
  const sourcePath = path.join(root, "source");
  const stateDir = path.join(root, "state");
  const stubPath = path.join(root, "acp-client-stub.sh");
  const project = "retry-accounting";

  try {
    await mkdir(sourcePath, { recursive: true });
    await mkdir(stateDir, { recursive: true });
    await mkdir(path.join(cpbRoot, "wiki", "system"), { recursive: true });
    await writeFile(path.join(cpbRoot, "wiki", "system", "dashboard.md"), "# Dashboard\n", "utf8");
    await writeRetryAccountingStub(stubPath);

    await execFileAsync(process.execPath, [
      "bridges/run-pipeline.mjs",
      "--project", project,
      "--task", "retry accounting regression",
      "--source-path", sourcePath,
      "--max-retries", "3",
    ], {
      cwd: process.cwd(),
      env: {
        ...process.env,
        CPB_ROOT: cpbRoot,
        CPB_ACP_CLIENT: stubPath,
        CPB_TEST_STATE: stateDir,
        CPB_WORKER_DISPATCH_ENABLED: "0",
      },
    });

    const eventsDir = path.join(cpbRoot, "cpb-task", "events", project);
    const [eventFileName] = await readdir(eventsDir);
    const eventFile = await readFile(path.join(eventsDir, eventFileName), "utf8");
    const phases = eventFile
      .split(/\r?\n/)
      .filter(Boolean)
      .map((line) => JSON.parse(line))
      .filter((event) => event.type === "phase_started")
      .map((event) => event.phase);

    assert.deepEqual(
      phases.filter((phase) => phase.startsWith("fix-")),
      ["fix-1", "fix-2"],
    );
    assert.ok(
      phases.includes("verify-retry-4"),
      "final PASS should run after stale evidence retry plus two executor fixes",
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
