import type { LooseRecord } from "../../../core/contracts/types.js";

type EventWorkflowDag = LooseRecord & {
  name?: string | null;
  nodes?: LooseRecord[];
  edges?: unknown[];
};

export type EventRecord = LooseRecord & {
  type?: string;
  ts?: string;
  phase?: string;
  agent?: string;
  jobId?: string;
  project?: string;
  nodeId?: string;
  kind?: string;
  artifactKind?: string;
  task?: string;
  workflow?: string;
  planMode?: string | null;
  executor?: unknown;
  queueEntryId?: string | null;
  indexSnapshotId?: string | null;
  sourceFingerprint?: string | null;
  indexFreshness?: unknown;
  planCache?: LooseRecord | null;
  parentPlanCache?: unknown;
  runPlan?: unknown;
  reason?: string | null;
  blockedReason?: string | null;
  error?: unknown;
  code?: string | number | null;
  status?: string | null;
  artifact?: unknown;
  attempt?: unknown;
  leaseId?: string | null;
  retryable?: boolean;
  retryCount?: number;
  maxRetries?: number | null;
  cause?: unknown;
  fromPhase?: string;
  worktree?: string | LooseRecord | null;
  path?: string | null;
  branch?: string;
  worktreeBranch?: string;
  baseBranch?: string;
  worktreeBaseBranch?: string;
  baseCommit?: string;
  worktreeBaseCommit?: string;
  worktreeOwnership?: LooseRecord;
  riskMap?: LooseRecord & {
    riskLevel?: unknown;
    verificationDepth?: unknown;
    adversarialRequired?: boolean;
    generatedAt?: unknown;
  };
  riskLevel?: unknown;
  domains?: unknown[];
  highRiskFiles?: unknown[];
  verificationDepth?: unknown;
  adversarialRequired?: boolean;
  adversarialFocus?: unknown[];
  phaseBudgetPolicy?: unknown;
  evidenceRequirements?: unknown[];
  confidence?: unknown;
  workflowDag?: EventWorkflowDag;
  nodes?: LooseRecord[];
  edges?: unknown[];
  dynamicAgentPlan?: LooseRecord & {
    riskLevel?: unknown;
    adversarialRequired?: boolean;
  };
  role?: string | null;
  category?: string | null;
  preferredAgent?: unknown;
  selectedAgent?: unknown;
  fallbackAgent?: unknown;
  fallbackAllowed?: unknown;
  fallbackApplied?: unknown;
  requested?: unknown;
  signals?: unknown[];
  upgradedQueueEntryId?: string | null;
  feedbackPath?: string | null;
  operation?: string | null;
  channels?: unknown[];
  timeoutAt?: string | null;
  round?: number;
  feedback?: unknown;
  retryQueueEntryId?: string | null;
  bundleId?: string | null;
  actor?: string | LooseRecord | null;
  prUrl?: string;
  pullRequestUrl?: string;
  url?: string;
  prNumber?: number;
  number?: number;
  instructions?: unknown;
  redirectEventId?: string | null;
  message?: unknown;
  remediationStatus?: string;
  outcome?: string | null;
  attemptId?: string | null;
  missingGates?: unknown[];
  checklistOutcome?: unknown;
  failedChecklistIds?: unknown[];
  uncheckedChecklistIds?: unknown[];
  missingEvidenceRefs?: unknown[];
  mismatchedEvidenceRefs?: unknown[];
  staleEvidenceRefs?: unknown[];
  poisonedEvidenceRefs?: unknown[];
  pollutedEvidenceRefs?: unknown[];
  pollutedOracleFiles?: unknown[];
  pollutedOracleFileCount?: number;
  completionReport?: unknown;
  runtimeFailureRefs?: unknown[];
  runtimeFailureCount?: number;
  unmappedChangedFiles?: unknown[];
  unmappedChangedFileCount?: number;
  assignmentId?: string | null;
  workerId?: string | null;
  model?: string | null;
  runtime?: string | null;
  queueId?: string | null;
  queuePriority?: unknown;
  concurrencyKey?: string | null;
  rateLimitedUntil?: string | number | null;
  heartbeatAt?: string | null;
  progressKind?: string | null;
  blocker?: unknown;
  failureType?: string | null;
  indexState?: unknown;
  mergeIndexStatus?: unknown;
  gitHead?: unknown;
  indexedFrom?: unknown;
  result?: unknown;
  verdict?: unknown;
  metadata?: LooseRecord;
  lineage?: LooseRecord;
  executorSelection?: LooseRecord;
  sourceContext?: LooseRecord | string | null;
  clearArtifacts?: string[];
};

export type EventStoreOptions = LooseRecord & {
  dataRoot?: string;
  legacyOnly?: boolean;
  includeLegacyFallback?: boolean;
  externalJournal?: boolean;
};

export type EventStreamCursor = {
  eventCount: number;
  eventDigest: string;
};

export type EventStreamDurabilityResult = {
  backend: "filesystem" | "redis";
  committed: true;
  exists: boolean;
  cursor: EventStreamCursor;
  file: string;
};

export type ConditionalEventAppendResult = {
  committed: boolean;
  conflict: boolean;
  cursor: EventStreamCursor;
};

export type EventWriteNotification = {
  cpbRoot: string;
  project: string;
  jobId: string;
  file: string;
  dataRoot: string | null;
  event: EventRecord;
};
