#!/usr/bin/env bash
set -euo pipefail

agent=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --agent)
      agent="${2:?missing value for --agent}"
      shift 2
      ;;
    --cwd)
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

prompt="$(cat)"
printf '%s\n' "$agent" >> "${FLOW_TEST_AGENT_LOG:?FLOW_TEST_AGENT_LOG is required}"
if [ -n "${FLOW_TEST_ENV_LOG:-}" ]; then
  printf '%s|%s|%s|%s|%s|%s\n' \
    "$agent" \
    "${ANTHROPIC_BASE_URL:-}" \
    "${ANTHROPIC_AUTH_TOKEN:-}" \
    "${ANTHROPIC_MODEL:-}" \
    "${ANTHROPIC_DEFAULT_SONNET_MODEL:-}" \
    "${ANTHROPIC_CUSTOM_MODEL_OPTION:-}" >> "$FLOW_TEST_ENV_LOG"
fi

output_file="$(
  printf '%s\n' "$prompt" |
    sed -n -E 's/^([0-9]+\. )?Write the (plan|deliverable|verdict) to: (.*)$/\3/p' |
    tail -1
)"

if [ -z "$output_file" ]; then
  echo "stub could not find output path in prompt" >&2
  exit 1
fi

mkdir -p "$(dirname "$output_file")"
case "$agent" in
  codex)
    if printf '%s\n' "$prompt" | grep -q "Give a verdict"; then
      printf 'PASS\nGenerated by ACP stub.\n' > "$output_file"
    else
      printf '# Plan\n\nGenerated by ACP stub.\n' > "$output_file"
    fi
    ;;
  claude)
    printf '# Deliverable\n\nGenerated by ACP stub.\n' > "$output_file"
    ;;
  *)
    echo "unexpected agent: $agent" >&2
    exit 1
    ;;
esac
