import {
  type ClassifiedRequirement,
  type ChecklistItem,
  type DocumentInput,
  type RequirementClassification,
  isRepoRelativePosixPath,
  recordArray,
  text,
} from "./checklist-shared.js";
import type { LooseRecord } from "../contracts/types.js";
import { freezeObservableContract } from "./observable-contract.js";

export type TaskRequirementSlice = {
  id: string;
  kind: "task_text";
  locator: string;
  text: string;
  acceptanceRelevant: true;
};

export function extractTaskRequirementSlices(task: unknown): TaskRequirementSlice[] {
  const taskText = text(task);
  if (!taskText) return [];
  const slices: TaskRequirementSlice[] = [{
    id: "REQ-001",
    kind: "task_text",
    locator: "task:0",
    text: taskText,
    acceptanceRelevant: true,
  }];
  let bulletIndex = 0;
  for (const line of taskText.split(/\r?\n/)) {
    const match = line.match(/^\s*(?:[-*+]\s+|\d+[.)]\s+)(\S.*)$/);
    if (!match) continue;
    const requirement = match[1].trim();
    if (requirement.length < 4) continue;
    bulletIndex += 1;
    slices.push({
      id: `REQ-TASK-BULLET-${bulletIndex}`,
      kind: "task_text",
      locator: `task:bullet:${bulletIndex}`,
      text: requirement,
      acceptanceRelevant: true,
    });
  }
  return slices;
}

export async function classifyAcceptanceRequirements({ task, documents = [] }: {
  task?: unknown;
  documents?: DocumentInput[];
  riskMap?: unknown;
}) {
  // V1 starts with deterministic source slices. Later prompt-assisted
  // classification may add richer spans, but checklist coverage must be
  // validated against this independent input, not against the checklist itself.
  return {
    schemaVersion: 1,
    classifiedRequirements: [
      ...extractTaskRequirementSlices(task),
      ...documents.map((doc: DocumentInput, index: number) => ({
        id: `REQ-DOC-${index + 1}`,
        kind: doc.kind || "document",
        locator: doc.locator || `document:${index}`,
        acceptanceRelevant: Boolean(text(doc.text || doc.content)),
      })),
    ].filter((entry) => entry.acceptanceRelevant),
  };
}

export async function buildAcceptanceChecklist({ jobId, project, task, documents = [], riskMap, requirementClassification, decomposedItems }: {
  jobId?: unknown;
  project?: unknown;
  task?: unknown;
  documents?: DocumentInput[];
  riskMap?: LooseRecord | null;
  requirementClassification?: RequirementClassification;
  decomposedItems?: unknown;
}) {
  // retain: dynamic — requirementClassification flows in from external sourceContext JSON
  // (optional classifiedRequirements per RequirementClassification); the cast narrows the
  // optional field to a required array. Downstream consumers still defend with `|| []`.
  const classification: RequirementClassification & { classifiedRequirements: ClassifiedRequirement[] } = (
    requirementClassification || await classifyAcceptanceRequirements({ task, documents })
  ) as RequirementClassification & { classifiedRequirements: ClassifiedRequirement[] };
  const risk = riskMap?.riskLevel === "high" ? "high" : "medium";
  const expectedEvidenceDefault = "method-specific evidence claim generated by a declared probe";
  // When the LLM decomposer supplies structured items (with allowedFiles scope),
  // build checklist items from them so the probe runner can match >0. Otherwise
  // fall back to the deterministic per-requirement map (allowedFiles:[]).
  const decomposedRecords = recordArray<ChecklistItem>(decomposedItems);
  const items = decomposedRecords.length > 0
    ? decomposedRecords.map((entry: ChecklistItem, index: number) => ({
        id: `AC-${String(index + 1).padStart(3, "0")}`,
        requirement: text(entry.requirement) || task,
        source: text(entry.source) || "task_text",
        sourceRefs: Array.isArray(entry.sourceRefs) && entry.sourceRefs.length > 0
          ? entry.sourceRefs
          : [{ kind: "task_text", locator: "task:0", sha256: null }],
        predicateId: text(entry.predicateId) || `PRED-${String(index + 1).padStart(3, "0")}`,
        required: true,
        area: text(entry.area) || "core",
        risk,
        verificationMethod: text(entry.verificationMethod) || "static",
        expectedEvidence: text(entry.expectedEvidence) || expectedEvidenceDefault,
        evidenceClass: text(entry.evidenceClass) || undefined,
        requiredEvidenceClass: text(entry.requiredEvidenceClass) || undefined,
        evidenceOrigin: text(entry.evidenceOrigin) || undefined,
        requiredEvidenceOrigin: text(entry.requiredEvidenceOrigin) || undefined,
        ...(typeof entry.requiresRealPathEvidence === "boolean" ? { requiresRealPathEvidence: entry.requiresRealPathEvidence } : {}),
        ...(entry.observableContract ? { observableContract: freezeObservableContract(entry.observableContract, index) } : {}),
        dependsOn: Array.isArray(entry.dependsOn) ? entry.dependsOn : [],
        allowedFiles: Array.isArray(entry.allowedFiles) ? entry.allowedFiles.filter((f: unknown) => isRepoRelativePosixPath(f)) : [],
      }))
    : (classification.classifiedRequirements || []).map((entry: ClassifiedRequirement, index: number) => ({
        id: `AC-${String(index + 1).padStart(3, "0")}`,
        requirement: text(entry.summary || entry.text || task),
        source: entry.kind || "task_text",
        sourceRefs: [{ kind: entry.kind || "task_text", locator: entry.locator, sha256: entry.sha256 || null }],
        predicateId: `PRED-${String(index + 1).padStart(3, "0")}`,
        required: true,
        area: "core",
        risk,
        verificationMethod: "static",
        expectedEvidence: expectedEvidenceDefault,
        dependsOn: [],
        allowedFiles: [],
      }));
  return {
    schemaVersion: 1,
    jobId: text(jobId),
    project: text(project),
    source: { task: text(task), issue: null, documents: documents.map((doc: DocumentInput) => doc.locator || doc.path).filter(Boolean).map(String), requirementClassificationArtifact: text(classification.artifact) || null },
    status: "frozen",
    items,
    assumptions: [],
  };
}
